### ISSUE TITLE
Verified badge gets cut off

### ISSUE THREAD

**Issue by Shayshon** [shashiirk/fake-tweet-generator#2]
I noticed after downloading that the verified badge gets cut off just by a little. This only happens after downloading and looks fine in preview. 
![tweet52123](https://user-images.githubusercontent.com/63425900/127927139-86217819-6b9b-4fac-9564-d6b715e0acdf.png)

**Comment by shashiirk** [comment]
I noticed it quite a long back and I'm expecting to fix it as soon as possible. Thanks for raising an issue because that will push me to work on it 😄.

**Comment by shashiirk** [comment]
Fixed it up.
