### ISSUE TITLE
can I use this library to make my own custom bulk images?

### ISSUE THREAD

**Issue by ItzmeSwapy** [shashiirk/fake-tweet-generator#9]
can you guide how can I use it?

**Comment by shashiirk** [comment]
bulk images as in?

**Comment by ItzmeSwapy** [comment]
Need to build a program that generates bulk tweet images.

Input Required:

Avatar - Type Image (Can be a single image or a directory containing multiple images - Random image should be selected it)
Name - Type Text ( Use Spintax to get random text values )
Username - Type Text ( Use Spintax to get random text values )
Tweet Date - Type Date (Range of date can be entered by the user. Program should generate a random date value )
Tweet Text - Type Text ( Use Spintax to get random text values )
Reply Count - Type Number (Range of reply numbers eg. 100 to 1000 can be entered by the user.Program should generate a random value )
Retweet Count - Type Number (Range of retweet eg. 10 to 100 can be entered by the user.Program should generate a random value )
Like Count - Type Number (Range of date eg. 1000 to 90000 can be entered by the user. Program should generate a random value )

This project just needs to run locally as the main aim is to generate bulk tweet images.

**Comment by alarcondgtuc** [comment]
That sounds... a bit sketchy or is it just me?
